### ISSUE TITLE
🚀 Create Database Models for Users and Their Favorite Lists! 🌟

### ISSUE THREAD

**Issue by Buddha-11** [opencodeiiita/FandomFusion-Backend#1]
## Issue Description  
Hey FandomFusion Fam! 🎉  

We're gearing up to make your experience here even more epic by setting up the foundation for our user and content database models! This will power your favorite feature—creating and sharing those iconic lists of anime, games, and movies. Let’s break it down:  

---

### 📝 User Model  
This model represents *you*—the amazing fans! Here's what it will include:  
- **`username`**: Your (unique) identifier in the FandomFusion universe.  
- **`email`**: Your identifier (unique) for technical stuff . 
- **`password`**: For keeping your accounts secure—because heroes always protect their identity. 🦸‍♂️  
- **References to the following list models:**  
  - **Anime List**  
  - **Game List**  
  - **Movie List**  
(Yes, your lists of favorite worlds will be directly linked to your profile!)  

---

### 📚 List Models  
Each list model (anime, games, movies) will hold:   
- **An array of content models** 
    - **Anime List** → Array of Anime Model 
  - **Game List**   → Array of Game Model 
  - **Movie List**  → Array of Movie Model 

> [!NOTE] 
> Three different list models are to be created (one each for movie list , game list , anime list) 

---

### 🎥 Anime Model (and similar for Games/Movies)  
This is where we detail your favorite anime:  
- **`publicDbId`**: The ID from the public database (because we're pulling this info from your favorite open APIs 📡).  
- **`status`**: Where are you on your anime journey? Choose from:  
  - *Planning to Watch/Play(for games)*  
  - *Watching/Playing(for games)*  
  - *Completed*  
  - *On Hold*  
- **`rating`**: Show some love (or shade) by rating the anime you watch! 🌟 (out of 10) 

> [!NOTE]
> Three different models are to be created (one each for movie , game , anime)
 
---

### Instructions for PR
- Add yourself in the [CONTRIBUTORS](CONTRIBUTORS.md) file before submitting your PR
- In the PR comment Add the relevant [Entity Relationship diagram](https://www.javatpoint.com/dbms-er-model-concept) for your implementation of models as an image
- Models should be in src/models and should follow the naming convention
 **{model name in camelCase}.model.js**
- Also make the relevant changes in the README.md (file directory structure)
- Add a test connection string in for mongoDB Atlas in .env and then add the images of the models created on the MongoDB Atlas Dashboard in the comment

**Comment by Sarvesh0955** [comment]
claim

**Comment by HGRgamer** [comment]
claim

**Comment by 07CalC** [comment]
claim

**Comment by apexcoder007** [comment]
claim

**Comment by Buddha-11** [comment]
@Sarvesh0955 assigned to you , do let me know if you need anything !!

**Comment by dark-dev2475** [comment]
claim

**Comment by spotnewmoon** [comment]
claim

**Comment by Skr-suyash** [comment]
claim

**Comment by ayush-patel1** [comment]
claim

**Comment by shubh5921** [comment]
claim

**Comment by MishtiGarg250** [comment]
claim
