### ISSUE TITLE
🌌  Task 5: Forge Your Heroic Identity – Add Profile Picture and Modify User Profile

### ISSUE THREAD

**Issue by Buddha-11** [opencodeiiita/FandomFusion-Backend#10]
Heroes of FandomFusion, the time has come to claim and customize your digital identity! Whether you’re a valiant anime watcher, an epic gamer, or a movie explorer, your **profile** is your banner in this vast realm of fandoms. 🌠  

In this quest, we shall enable:  
- **Profile customization**: Allow users to update their **username**, **email**, and **profile picture**.  
- **Profile retrieval**: Add the ability to fetch user details using their **ID**.  

By harnessing the power of **Cloudinary** and **Multer**, our heroes will have seamless control over their digital banners (profile pictures).  

---

## **🛠️ Task Overview**  

We need to:  
1. Add support for uploading **profile pictures** using **Cloudinary** and **Multer**.  
2. Create a **route** for modifying user profiles (username, email, and profile picture).  
3. Allow users to update **all fields or just a single field**, ensuring the rest remain unchanged.  
4. Implement a new **controller function** to fetch a user’s details by their **ID**.  
5. Set a **default profile picture** during user registration.  
  

---

### **1. Update the User Model**  
- Add a `profileImg` field to the User model to store the image URL.  
- Ensure that a default profile picture URL is set for users who register without uploading an image.  
- **File to Update**: `src/models/user.model.js`  

---

### **2. Configure Cloudinary**  
- Integrate **Cloudinary** for cloud-based image storage.  
- Add the Cloudinary credentials (`CLOUDINARY_CLOUD_NAME`, `CLOUDINARY_API_KEY`, `CLOUDINARY_API_SECRET`) in the `.env` file.  
- Set up a utility to configure and export Cloudinary for use across the project.  
- **File to Create**: `src/utils/cloudinary.js`  

---

### **3. Configure Multer for File Uploads**  
- Set up **Multer** to handle file uploads.  
- Configure the middleware to validate file types and ensure only images are accepted.  
- Prepare for integration with Cloudinary by **skipping local file storage**.  
- **File to Create**: `src/middleware/upload.middleware.js`  

---

### **4. Create the Modify Profile Route**  
- Add a **PATCH route** to allow authenticated users to update their username, email, or profile picture.  
- Ensure users can update **all fields or just one field** at a time.  
   - For example, if a user only updates their username, the email and profile picture should remain untouched.  
- Integrate the `authVerify` middleware to ensure only logged-in users can modify their profile.  
- Connect the route to the profile modification controller.  
- **File to Update**: `src/routes/v1/user.routes.js`  

---

### **5. Implement the Modify Profile Controller**  
- Write a controller to handle profile updates:  
   - Upload the new profile image to Cloudinary if provided.  
   - Allow updates for **username**, **email**, and **profileImg** independently.  
   - Ensure that if a user updates only one field (e.g., username), the rest of the profile data remains the same.  
- Handle errors gracefully, ensuring that only valid inputs are accepted.  
- **File to Create**: `src/controllers/userProfile.controller.js`  

---
### **6. Implement the Get User by ID Controller**  
- Write a new controller function to fetch user details using their **ID**:  
   - Retrieve the user document by ID from the database.  
   - Return the user’s details (excluding sensitive information like the password).  
   - Return an appropriate error if the user does not exist.  
- Add a **GET route** to retrieve user details by ID.  
- **Files to Update**:  
   - `src/controllers/userProfile.controller.js` – Add the new controller function.  
   - `src/routes/v1/user.routes.js` – Add the GET route for fetching user details.  
   - 
  ---
### **7. Test the Flow**  
- Verify the following:  
   - A user can update their **username**, **email**, or **profile picture** individually or all fields at once.  
   - If a field is not included in the request, it should remain unchanged in the database.  
   - A user can successfully retrieve their details using their **ID**.  
   - Proper error messages are returned for invalid file types, unauthorized access, or non-existent users.  
- Test the routes with tools like **Postman** or **Insomnia**.  
   - **Modify Profile**:  
     - **Method**: `PATCH`  
     - **Route**: `/api/v1/user/profile`  
     - **Headers**: Authorization token.  
     - **Body**: Form data including `username`, `email`, and `profileImg` (file).  
   - **Get User by ID**:  
     - **Method**: `GET`  
     - **Route**: `/api/v1/user/:id`  
     - **Headers**: Authorization token.  

---

### **Instructions for PR**
 -  Attach the screenshots of the responses on Postman
 - DM on discord for the current .env
 - Test the functioning of the profile update feature by sending a GET request for a user before and after the changes , verify and attach the screenshots
 - Add the new endpoints in the [API_ENDPOINTS.md]([API_ENDPOINTS.md) 
 - As this issue requires many steps , I have assigned enough points , do hit me up on discord for any help tho :)

---

**Comment by 07CalC** [comment]
Claim

**Comment by HGRgamer** [comment]
Claim
