### ISSUE TITLE
✨ Task 6: Expanding the Realm – Adding Media to User Lists ✨

### ISSUE THREAD

**Issue by Buddha-11** [opencodeiiita/FandomFusion-Backend#12]
Greetings, Fusioneers! The time has come to let users shape their realms by adding their favorite **Anime**, **Games**, or **Movies** to personalized lists. Let's dive into the magic of building this feature! 🌌  

---

## 📝 Task Description  

Your task is to implement the functionality that allows users to add media items (Anime, Games, or Movies) to their respective lists. 
---

### **1. Controller Functions**  

Create controller functions to handle the addition of media to the respective lists.  

**File to update:** `src/controllers/userLists.controllers.js`  

**Functions to Implement**:  
- **`addAnimeToList`**:  
  - Accepts `publicDbId`, `status`, and `rating` as input in req.body .  
  - Checks if the Anime is already referenced in the  **AnimeList model** of the user. If not, creates a new anime entry.  
  - Adds a reference to this Anime in the **AnimeList model** associated with the user.  
  - Send a success/failure response .

- **`addGameToList`**:  
  - Similar to `addAnimeToList`, but for Games and the **GameList model**.  

- **`addMovieToList`**:  
  - Similar to `addAnimeToList`, but for Movies and the **MovieList model**.  

---

### **2. Set Up Routes**  

Define routes to connect the controllers to the frontend.  

**Endpoints to Implement:**  
- `POST /api/v1/lists/anime/add` → Add an anime to the list.  
- `POST /api/v1/lists/games/add` → Add a game to the list.  
- `POST /api/v1/lists/movies/add` → Add a movie to the list.  
- Make sure the routes are protected with the present middleware

**File to update:** `src/routes/v1/userLists.routes.js`  

---

### **3. Test and Validate**  

Ensure the flow is smooth and error-free:  
1. Validate the input fields (`publicDbId`, `status`, `rating`).  
2. Prevent duplicate entries in the lists.  
3. Test scenarios for both existing and new entries in media models.  
4. Make sure both success and failure responses are send

---

### ✨   Instructions for PR
- Attach relevant Postman screenshots 
- make required changes in [API_ENDPOINTS.md](API_ENDPOINTS.md) for the new routes
- Make required changes in directory structure in the [README.md](README.md)
- DM on discord for the current .env

**Comment by official-ashutosh** [comment]
Claim

**Comment by Buddha-11** [comment]
@official-ashutosh assigning you !

**Comment by ayush-patel1** [comment]
claim

**Comment by ayush-patel1** [comment]
assign it to me
