### ISSUE TITLE
🛠️Task 7: Forge Your Fandom - Update and Remove Media Items from Personalized Lists! 🌟

### ISSUE THREAD

**Issue by Buddha-11** [opencodeiiita/FandomFusion-Backend#19]
## 📝 Task Description  

Your mission is to implement the following functionalities:  
1. **Updating Media Details**: Users can update **status** and/or **rating** for a specific Anime, Game, or Movie using its MongoDB ID.  
2. **Removing Media Items**: Users can remove an item from their respective lists and delete the entry from the Media database if it’s no longer referenced.  

---

### **1. Controller Functions**  

Create controller functions to handle updates and removals based on MongoDB IDs passed as route parameters.  

**File to update:** `src/controllers/userLists.controllers.js`  

**Functions to Implement**:  
- **`updateAnimeInList`**:  
  - Accepts `status` and/or `rating` in `req.body` and the Anime's MongoDB ID as a route parameter (`req.params.id`).  
  - Finds the Anime in the user's **AnimeList model** using the MongoDB ID and updates the specified fields.  
  - Respond with success or failure.  

- **`updateGameInList`** and **`updateMovieInList`**:  
  - Same as `updateAnimeInList` but for Games and Movies, referencing the **GameList model** and **MovieList model**, respectively.  

- **`removeAnimeFromList`**:  
  - Accepts the Anime's MongoDB ID as a route parameter (`req.params.id`).  
  - Removes the Anime reference from the user's **AnimeList model**.  
  - Deletes the corresponding Anime entry from the **Anime model** if it is no longer referenced by any user's list.  
  - Respond on success/failure and perform error handling for multiple causes of failure

- **`removeGameFromList`** and **`removeMovieFromList`**:  
  - Same as `removeAnimeFromList` but for Games and Movies, referencing their respective models.

---

### **2. Set Up Routes**  

Define routes to connect the controllers to the frontend.  

**Endpoints to Implement:**  
- `PATCH /api/v1/lists/anime/update/:id` → Update an anime in the list.  
- `PATCH /api/v1/lists/games/update/:id` → Update a game in the list.  
- `PATCH /api/v1/lists/movies/update/:id` → Update a movie in the list.  
- `DELETE /api/v1/lists/anime/remove/:id` → Remove an anime from the list.  
- `DELETE /api/v1/lists/games/remove/:id` → Remove a game from the list.  
- `DELETE /api/v1/lists/movies/remove/:id` → Remove a movie from the list.  
- Ensure all routes are protected by the `authVerify` middleware.

**File to update:** `src/routes/v1/userLists.routes.js`  

---

### **3. Test and Validate**  

Thoroughly test the implemented features:  
1. Validate `id` parameters and `req.body` fields (`status`, `rating`).  
2. Ensure partial updates work (e.g., updating only `status` or `rating`).  
3. Confirm that media removal deletes the reference from the user's list and removes the media entry from the database if unreferenced.  
4. Check all success and failure responses for consistency.  
5. Test edge cases like invalid IDs, missing parameters, or duplicate updates.

---

### **4. Documentation Updates**  

- Update [API_ENDPOINTS.md](API_ENDPOINTS.md) with the new routes and their parameters.  
- Reflect changes in the [README.md](README.md) directory structure.  

---

### ✨   Instructions for PR  
- Include Postman screenshots for successful updates and deletions.  
- Ensure all code follows the project's style guide and standards.  
- DM on Discord for access to the current `.env` file.

**Comment by HGRgamer** [comment]
claim

**Comment by Buddha-11** [comment]
@Darkknight0125 assigned to you !!

**Comment by ayush-patel1** [comment]
claim
