### ISSUE TITLE
🌌 Task 8: Harness the Power of Search - Integrate Jikan API to Enrich the Anime Database! 🎥✨

### ISSUE THREAD

**Issue by Buddha-11** [opencodeiiita/FandomFusion-Backend#21]
## 📝 Task Description

The objective is to enhance the backend by integrating the Jikan API to provide anime search functionality. The search results will be refined and returned to the frontend with only the necessary fields.

---

### 1. Fetch Anime Data from Jikan API

- **Goal**: Retrieve anime search results from Jikan API using a query string.

- **API**: Understand the required Jikan api endpoint [here](https://docs.api.jikan.moe/#tag/anime/operation/getAnimeSearch)
  
- **File to Update**: `src/controllers/media.controllers.js`

#### Steps:
1. Create a function `searchAnime` in the controller.
2. Accept the query parameter from `req.query.q`.
3. Make a `GET` request to the Jikan API using the query parameter.
   - **Endpoint**: `GET https://api.jikan.moe/v4/anime?q={search_query}`
4. Implement error handling for:
   - API failures
   - Invalid responses
   - Empty results

---

### 2. Refine the API Response

- **Goal**: Modify the API response to only return the desired fields.

- **File to Update**: `src/utils/responseFormatters.js`

#### Fields to Include:
- `publicDbId`: Use `mal_id` from Jikan API response.
- `imageUrl`: Use `images.jpg.large_image_url`.
- `title_english`
- `title_japanese`
- `episodes`
- `status`
- `score`
- `synopsis`
- `rated`: Use `rating`.
- `season`
- `year`
- `type`: Set to "anime".

#### Steps:
1. Create a helper function `formatAnimeResponse`.
2. Map through the Jikan API response and format the fields as needed.
3. Return the formatted data.

---

### 3. Send Refined Data to the Frontend

- **Goal**: Return the refined anime data to the frontend.

#### Steps:
1. Update the `searchAnime` controller to call `formatAnimeResponse`.

#### Example Response:
```json
{
  "data": [
    {
      "publicDbId": 38000,
      "imageUrl": "https://cdn.myanimelist.net/images/anime/1286/99889l.jpg",
      "title_english": "Demon Slayer: Kimetsu no Yaiba",
      "title_japanese": "鬼滅の刃",
      "episodes": 26,
      "status": "Finished Airing",
      "score": 8.45,
      "synopsis": "Ever since the death of his father...",
      "rated": "R - 17+ (violence & profanity)",
      "season": "spring",
      "year": 2019,
      "type": "anime"
    }
  ]
}
```
### Goal: 
Define a route to handle anime search requests.

### File to Update: 
`src/routes/v1/media.routes.js`

### Steps:

1. **Create a route that calls the searchAnime controller.**
    - **Endpoint:** `GET /api/v1/media/anime/search`

2. **Add necessary middleware for route protection**

---

### Goal: 
Ensure the anime search feature works correctly under various scenarios.

### Test Cases:

1. **Validate the `q` query parameter.**
2. **Test the API response with various search queries.**
3. **Handle edge cases like invalid queries or empty results.**

---

### Files to Update:

- **`API_ENDPOINTS.md`:** Add details of the new search endpoint.
- **`README.md`:** Update with any changes in directory structure or setup instructions.

---

## ✨ Instructions for Pull Request

1. Include **screenshots from Postman** tests for both successful and failed searches.
2. Ensure the code follows the **project’s style guide** and coding standards.
3. DM on Discord to request access to the `.env` file 
4. Understand the response of Jikan api [here](https://docs.api.jikan.moe/#tag/anime/operation/getAnimeSearch)

**Comment by ayush-patel1** [comment]
claim

**Comment by ayush-patel1** [comment]
claim please assign it to me

**Comment by Buddha-11** [comment]
@Debankur04 assigned to you !! ping me on discord for any help :)

**Comment by ayush-patel1** [comment]
@Buddha-11 this is unfair

**Comment by Buddha-11** [comment]
> @Buddha-11 this is unfair

Why is it so ? it is an first come first serve basis issue and @Debankur04 claimed it first

**Comment by ayush-patel1** [comment]
just a second issue due to netwrok

**Comment by Buddha-11** [comment]
@Debankur04 Status on the progress ?

**Comment by ayush-patel1** [comment]
@Buddha-11 please assign it to me I have already gone through ussue

**Comment by Debankur04** [comment]
@Buddha-11 I have gone through the issue and already started working.

@ayush-patel1 brother I understand your situation, but please understand this is a fcfs issue. 😃

**Comment by Buddha-11** [comment]
@Debankur04  DM me on discord for the `.env`

**Comment by Buddha-11** [comment]
@Debankur04 You have to finish the issue till EOD ,or else it will be assigned to the next contributor !!

**Comment by Buddha-11** [comment]
@HGRgamer assigning to you as the previous assignee wasn't able to complete the issue due to some unforeseen situation

**Comment by ayush-patel1** [comment]
@Buddha-11 after @Debankur04  i was first to claim why not assigned to me?

**Comment by Buddha-11** [comment]
> @Buddha-11 after @Debankur04 i was first to claim why not assigned to me?

![image](https://github.com/user-attachments/assets/94e5cedc-e3e3-49ba-b7fe-a05555212240)
I am following the guidelines here , I assign only on the order of the claim comments I get on the issue

**Comment by ayush-patel1** [comment]
okay!!

**Comment by ayush-patel1** [comment]
who is assigned this issue?
