### ISSUE TITLE
Quick , improve the documentation

### ISSUE THREAD

**Issue by Buddha-11** [opencodeiiita/FandomFusion-Backend#23]
## 📝 Problem Description

The `API_ENDPOINTS.md` file seems to have formatting issues, making it difficult to read or parse through the API documentation effectively. Additionally, the endpoints for **user registration** are not documented in the file.

### Formatting Issues
- Headers not properly styled (e.g., missing `#` or incorrect hierarchy). Add all the list related endpoints under a List Endpoints section
 ![Image](https://github.com/user-attachments/assets/a9e15c88-9416-4c19-ae19-9f51b08206dd)

- Missing sections or unordered listing.
- Code sections not formatted correctly ![Image](https://github.com/user-attachments/assets/13f22cb4-9753-4358-9c4f-d8a850d68544)

### Missing Endpoints
The following user-related endpoints need to be added to the file:
1. **POST /api/v1/auth/register**  
   - **Description**: Register a new user.
   - Go through the logic in the controller file to find all the responses and add them to the documentation

---

## ✅ Expected Outcome

1. Fix formatting issues in `API_ENDPOINTS.md` to ensure a clean and readable structure.
2. Add the missing **user registration ** with detailed documentation.
3. Verify all endpoints are updated and organized under relevant sections.

---

## Instruction for PR 
- Before making a PR confirm the changes made with me on discord

**Comment by PriyamJChakrabarty** [comment]
Claim

**Comment by Buddha-11** [comment]
@Darkknight0125 assigned to you , hoping for a quick PR :)
