### ISSUE TITLE
📝 Task 9: Implement "Get Anime List" Functionality

### ISSUE THREAD

**Issue by Buddha-11** [opencodeiiita/FandomFusion-Backend#25]
## **Objective**
Create a `getAnimeList` function in the `userList.controller.js` file to fetch the user's anime list. The function should:
1. Retrieve anime entries from the database.
2. Query the Jikan API using the `publicDbId` for detailed anime information.
3. Use a formatter function in `utils/responseFormatter.js` to standardize the response.
4. Return the enriched data to the client.

---

### **1. Create `getAnimeList` Function**

**File**: `src/controllers/userList.controller.js`  
**Steps**:
1. Retrieve the user's `animeList` from the database using `req.user.id`.
2. Iterate through the `animeList` and make a GET request to the Jikan API for each anime using the `publicDbId`.
   - **Jikan API Endpoint**: `GET https://api.jikan.moe/v4/anime/{id}`
3. Combine the Jikan API response with the `status` and `rating` fields from the database.
4. Use the `formatAnimeListResponse` function to standardize the enriched data.
5. Return the formatted response to the frontend.

---

### **2. Create/Update Formatter Function**

**File**: `src/utils/responseFormatter.js`  
**Function Name**: `formatAnimeListResponse`  
**Steps**:
1. Accept two inputs: the Jikan API response and the `animeList` database entry.
2. Combine the following fields:
   - **Jikan Fields**:
     - `publicDbId`: From `mal_id`.
     - `imageUrl`: From `images.jpg.large_image_url`.
     - `title_english`, `title_japanese`, `episodes`, `status`, `score`, `synopsis`, `rated`, `season`, `year`, `type`.
   - **Database Fields**:
     - `status`: User-defined status (e.g., `Watching`, `Completed`).
     - `rating`: User-defined rating.
3. Return the formatted object.

---

### **3. Define the Route**

**File**: `src/routes/v1/userList.routes.js`  
**Endpoint**: `GET /api/v1/list/anime`  
**Middleware**: Use `authMiddleware` to authenticate the user.  
**Steps**:
1. Create a new route for `GET /api/v1/list/anime`.
2. Link the route to the `getAnimeList` function in `userList.controller.js`.
3. Ensure `authMiddleware` is used to protect the route.

---

## **Example Response**

```json
{
  "data": [
    {
      "publicDbId": 38000,
      "imageUrl": "https://cdn.myanimelist.net/images/anime/1286/99889l.jpg",
      "title_english": "Demon Slayer: Kimetsu no Yaiba",
      "title_japanese": "鬼滅の刃",
      "episodes": 26,
      "status": "Finished Watching",
      "score": 8.45,
      "synopsis": "Ever since the death of his father...",
      "rated": "R - 17+ (violence & profanity)",
      "season": "spring",
      "year": 2019,
      "type": "anime",
      "userStatus": "Completed",
      "userRating": 9
    }
  ]
}
```
# 🛠️ Test the Implementation

## **1. Create Test Data**
- **Step 1**: Create a user in the database.
- **Step 2**: Add two anime entries to their `animeList`:
  - **Anime 1**:
    - `publicDbId`: `38000`
    - `status`: `"Completed"`
    - `rating`: `9`
  - **Anime 2**:
    - `publicDbId`: `459`
    - `status`: `"Watching"`
    - `rating`: `8`

---

## **2. Validate API Functionality**
- **Step 1**: Make a `GET` request to the new endpoint:  
  **Endpoint**: `/api/v1/anime/list`
- **Step 2**: Verify the following:
  1. The response includes enriched data from both the **Jikan API** and the **database**.
  2. The `status` and `rating` fields in the response match the database values.
  3. All fields from the **Jikan API** are correctly mapped.

---

## **Expected Response Example**
```json
{
 "data" : [
    {
      "publicDbId": 38000,
      "imageUrl": "https://cdn.myanimelist.net/images/anime/1286/99889l.jpg",
      "title_english": "Demon Slayer: Kimetsu no Yaiba",
      "title_japanese": "鬼滅の刃",
      "episodes": 26,
      "status": "Finished Watching",
      "score": 8.45,
      "synopsis": "Ever since the death of his father...",
      "rated": "R - 17+ (violence & profanity)",
      "season": "spring",
      "year": 2019,
      "type": "anime",
      "userStatus": "Completed",
      "userRating": 9
    },
    {
      "publicDbId": 459,
      "imageUrl": "https://cdn.myanimelist.net/images/anime/1276/98885l.jpg",
      "title_english": "Attack on Titan",
      "title_japanese": "進撃の巨人",
      "episodes": 25,
      "status": "Airing",
      "score": 9.15,
      "synopsis": "After his hometown is destroyed...",
      "rated": "R - 17+ (violence & profanity)",
      "season": "winter",
      "year": 2013,
      "type": "anime",
      "userStatus": "Watching",
      "userRating": 8
    }
  ]
}
```
---
## **Instructions for PR**
- Add the screenshots of success and failure responses of postman to the PR
- make the required changes in the [API_ENDPOINTS.md](API_ENDPOINTS.md) , add under the anime List section
- DM on discord for the `.env`

**Comment by Darkknight0125** [comment]
Claim

**Comment by Snehalgupta-07** [comment]
Claim

**Comment by Snehalgupta-07** [comment]
Claim

**Comment by official-ashutosh** [comment]
Claim
