### ISSUE TITLE
🛠️ Implement Friend Request Feature , Upgrade to websockets !!

### ISSUE THREAD

**Issue by Buddha-11** [opencodeiiita/FandomFusion-Backend#27]
# ⚙️ Implementation Steps

> [!NOTE]
> This issue requires knowledge of websockets being implemented through socket.io , please only claim if you have used websockets/socket.io before

## 1. Update the User Model

Add a new field to the User model to track a user's friends.

- **File to update:** `src/models/user.model.js`

  - **friends:** An array of references to User IDs that represent a user's friends.

## 2. Create the Friend Request Model

Define a schema to handle friend requests.

- **File to create:** `src/models/friendRequest.model.js`

### Schema Fields:

- **sender:** Reference to the User who sent the request.
- **recipient:** Reference to the User who received the request.
- **status:** String to indicate the request's status (pending, accepted, rejected).
- **timestamps:** Automatically generated fields to track when the request was created and updated.

## 3. Create friendRequest.controller.js

Implement controller functions to manage friend request operations.

- **File to create:** `src/controllers/friendRequest.controller.js`

### Functions to Implement:

- **sendFriendRequest:**
  - Save a friend request to the database.
  - Check for duplicate requests.
  - Send a real-time notification to the recipient using Socket.IO.

- **getFriendRequests:**
  - Retrieve all friend requests for the logged-in user.
  - Populate the sender's information (e.g., username, profile picture).

- **respondToFriendRequest:**
  - Handle accepting or rejecting a friend request.
  - Update both users' friend lists if the request is accepted.
  - Send a real-time notification to the sender.

## 4. Update Routes

Define routes to connect the controller functions with the frontend.

- **File to update:** `src/routes/v1/user.routes.js`

### Endpoints to Implement:

- **POST /friend-requests:** Send a friend request.
- **GET /friend-requests:** Retrieve all friend requests for the logged-in user.
- **POST /friend-requests/respond:** Accept or reject a friend request.

## 5. Real-Time Integration with Socket.IO

Integrate Socket.IO functionality directly into the controller to handle real-time notifications.

- **File to update:** `src/controllers/friendRequest.controller.js`

### Events to Emit:

- **friendRequestReceived:** Notifies the recipient of a new friend request.
- **friendRequestResponse:** Notifies the sender when their friend request is accepted or rejected.

## 6. Update app.js

Initialize Socket.IO and attach it to the Express app.

- **File to update:** `app.js`

  - Initialize Socket.IO and pass the io instance to req.app for use in controllers.

## 7. Create Test File (socket_test.html)

Create a basic frontend to test real-time functionality.

- **File to create:** `public/socket_test.html`

### Requirements:

- The UI should display a list of incoming friend requests with "Accept" and "Reject" buttons.
- Include a field to send friend requests by entering the recipient's username.

### REST API Testing

Use Postman to test the following:

- **Send Friend Request:**
  - **Endpoint:** `POST /api/v1/user/friend-requests`
  - **Request Body:** `{ "recipientId": "<recipientId>" }`
  - **Expected Response:** `{ "message": "Friend request sent.", "friendRequest": {...} }`
  
- **Get Friend Requests:**
  - **Endpoint:** `GET /api/v1/user/friend-requests`
  - **Expected Response:** List of friend requests with sender information.
  
- **Respond to Friend Request:**
  - **Endpoint:** `POST /api/v1/user/friend-requests/respond`
  - **Request Body:** `{ "requestId": "<requestId>", "action": "accept" }`
  - **Expected Response:** `{ "message": "Friend request accepted." }`

### Real-Time Testing

- Open `socket_test.html` in two browser tabs.
- Use one tab to send a friend request.
- Verify that the second tab receives a real-time notification.
- Respond to the friend request and verify updates in real time.

## 📂 File Changes

- **Models:**
  - `src/models/user.model.js`: Add the friends field.
  - `src/models/friendRequest.model.js`: Create the FriendRequest model.

- **Controllers:**
  - `src/controllers/friendRequest.controller.js`: Implement REST API and real-time logic.

- **Routes:**
  - `src/routes/v1/user.routes.js`: Add routes for friend request functionality.

- **Socket.IO Integration:**
  - `app.js`: Initialize and attach Socket.IO to the app.

- **Testing:**
  - `public/socket_test.html`: Test real-time features.

## 🏁 Expected Outcome

- Users can send, view, and respond to friend requests.
- Notifications are delivered in real time.
- Friend lists are updated automatically on acceptance.
- All functionality works seamlessly with both REST API and real-time features.

## **Instructions for PR**
- Add the screenshots/or a short video showcasing working of real time friend request notification
- Add the screenshots of the database to verify if the friend request is being stored or not
- Add screenshots for failure cases too. 
- Make required changes in [API_ENDPOINTS.md](API_ENDPOINTS.md)
- Update the directory structure in [README.md](README.md)
- DM on discord for the `.env`

**Comment by Darkknight0125** [comment]
Claim

**Comment by rajbir40** [comment]
Claim

**Comment by Buddha-11** [comment]
@Darkknight0125 assigned to you !! , stay connected on discord as this issue covers a lot , hit me up if any doubts

**Comment by PriyamJChakrabarty** [comment]
Claim

**Comment by ayush-patel1** [comment]
claim
