### ISSUE TITLE
🌌 Task : Harness the Power of Search - Integrate RAWG API to Enrich the Games Database! ✨

### ISSUE THREAD

**Issue by Buddha-11** [opencodeiiita/FandomFusion-Backend#28]
# Description
Add functionality to search for games using the RAWG API. The search results will be transformed into a specific format and served via a protected API endpoint.

### 1. Environment Configuration
Ensure the following environment variables are present in the `.env` file:
- `RAWG_URL`: Base URL for the RAWG API.
- `RAWG_KEY`: API key for authentication with the RAWG API.

#### a. Controller: `media.controller.js`
- **Function to Add**: `searchGame`
- **Responsibilities**:
  - Parse the incoming search query from `req.query`.
  - Make a request to the RAWG API using the search term with query params key=RAWG_KEY.
  - Understand the response of the RAWG API [here](https://api.rawg.io/docs/#operation/games_list)
  - Use the `formatGameSearchResponse` function from `utils/responseFormatter.js` to transform the API response into the desired format.
  - Handle potential errors, such as:
    - Missing or invalid API key.
    - RAWG API returning an error or no results.

#### b. Utils: `responseFormatter.js`
- **Function to Add**: `formatGameSearchResponse`
- **Responsibilities**:
  - Extract relevant fields from the RAWG API response (`id`, `name`, `released`, `background_image`, `rating`, `genres`, `platforms`).
  - Structure the data in the specified format:

    ```json
    {
      "publicDbId": <id>,
      "title": <name>,
      "releasedDate": <released>,
      "imgUrl": <background_image>,
      "score": <rating>,
      "genre": [<genre_names>],
      "platform": [<platform_names>]
    }
    ```
> [!NOTE]
> in genre and platform only the name is required , rest of the data should be filtered out 
  - Handle cases where data fields might be missing or incomplete.

#### c. Routes: `routes/v1/media.routes.js`
- **Route to Add**: `/game/search`
- **HTTP Method**: GET
- **Middleware**: Protect the route using `userAuthMiddleware`.
- **Controller Function**: Attach the `searchGame` function to this route.

#### a. Unit Testing
- Test `searchGame` to ensure it:
  - Calls the RAWG API with the correct parameters.
  - Returns properly formatted data.
  - Handles errors gracefully.

#### b. Integration Testing
- Test the `/game/search` endpoint with authenticated requests to verify:
  - Correct handling of valid and invalid queries.
  - Proper integration of the `searchGame` and `formatGameSearchResponse` functions.

#### Request:
```http
GET api/v1/media/game/search?search=<game_name>
Authorization: Bearer <user_token>
```
#### Response 
```json
{
  "status": "success",
  "data": [
    {
      "publicDbId": 12345,
      "title": "Game Name",
      "releasedDate": "2024-01-01",
      "imgUrl": "https://example.com/image.jpg",
      "score": 4.5,
      "genres": ["Action", "Adventure"],
      "platforms": ["PC", "PlayStation"]
    }
  ]
}
```
---
## **Instructions for PR**
- Add the screenshots of success and failure responses of postman to the PR
- make the required changes in the [API_ENDPOINTS.md](API_ENDPOINTS.md) , add under the anime List section
- DM on discord for the `.env`
- You can reference Issue: #21  its more or less similar , just with a different api for anime

**Comment by ayush-patel1** [comment]
claim

**Comment by PriyamJChakrabarty** [comment]
Claim

**Comment by Buddha-11** [comment]
@ayush-patel1 assigned to you , DM on discord for the `.env`

**Comment by ayush-patel1** [comment]
@Buddha-11 check dm on discord
