### ISSUE TITLE
🎯 Task 2: Register Users for the FandomFusion Realm

### ISSUE THREAD

**Issue by Buddha-11** [opencodeiiita/FandomFusion-Backend#3]
Welcome to the Registration Station of **FandomFusion**, where fans create their ultimate identities to join our vibrant community! 🌟  

---

### **What You’ll Do**  
- Create the registration controller in `src/controllers/userAuth.controllers.js`.  
- Handle user input: `username`, `email`, and `password`.  
- Encrypt the password using `bcrypt` with **10 salt rounds** for enhanced security.  
- Implement the `/api/v1/auth/register` route in `src/routes/v1/userAuth.routes.js` to point to the controller.  

### **Steps to Achieve This**  
1. **Build the Registration Controller**  
   - **File:** `src/controllers/userAuth.controllers.js`  
   - **Logic:**  
     - Validate the form inputs: `username`, `email`, and `password`.  
     - Encrypt the password using `bcrypt`.  
     - Add the user to the **User model**.  
     - Respond with a success message:  
       - *"Welcome to the FandomFusion Realm! Your identity has been secured. Start creating and sharing your lists today!"*  

2. **Update the Route**  
   - **File:** `src/routes/v1/userAuth.routes.js`  
   - Add the `/api/v1/auth/register` route and bind it to the registration controller.

---

### **Key Objectives**  
- **Security First:**  
  - Ensure password encryption with `bcrypt` (10 salt rounds).  
  - Validate user input to avoid bad data in the database.  

- **Fan-First Experience:**  
  - Display a welcoming message upon successful registration:   

- **Database Integration:**  
  - Insert the new user into the `User` model.  

---

### **Example Response on Success**  
```json
{
  "status": "OK",
  "message": "Registered Successfully",
  "data": {
    "All the data from server will be here"
  }
}
```
---
### **Instructions for PR**
- Use postman for validating the endpoints
- Add a screenshot of the response when the POST request is sent 
- Make changes in [API_ENDPOINTS.md]([API_ENDPOINTS.md)
- DM on discord for DB url

**Comment by HGRgamer** [comment]
claim

**Comment by Buddha-11** [comment]
@HGRgamer assigned to you , DM on discord for the current .env

**Comment by Sarvesh0955** [comment]
claim
