### ISSUE TITLE
🔑 Task 3: User Login – Enter the Gateway to FandomFusion

### ISSUE THREAD

**Issue by Buddha-11** [opencodeiiita/FandomFusion-Backend#5]
Welcome, adventurers! 🌌 The Gateway to the **FandomFusion Realm** awaits, where fans unite to explore and share their favorite anime, games, and movies. But before you step through, you must prove your identity and earn your place among the fans!  

---

### **What You’ll Do**  
- Implement the **User Login functionality** in `src/controllers/userAuth.controllers.js`.  
- Create a route at `/api/v1/auth/login` in `src/routes/v1/userAuth.routes.js`.  
- Authenticate users using their **username** and **password**.  
- Securely verify the encrypted password stored in the database.  

---

### **Steps to Achieve This**  
1. **Build the Login Controller**  
   - **File:** `src/controllers/userAuth.controllers.js`  
   - **Logic:**  
     - Accept `username` and `password` as input from the user.  
     - Look up the user in the database by their username.  
     - Use `bcrypt` to verify the provided password against the stored encrypted password.  
     - On successful authentication:  
       - Generate a **JWT token** to maintain the user session.  
       - Return a `200` status with a success message:  
         - *"User Logged in successfully"*  
     - On failure:  
       - Return an appropriate error messages  depending on the case of failure.

2. **Update the Route**  
   - **File:** `src/routes/v1/userAuth.routes.js`  
   - Add the `/api/v1/auth/login` route and bind it to the login controller.

---

### **Key Objectives**  
- **Secure Fan Access:**  
  - Ensure the use of **JWT tokens** for session management and secure access to protected routes.  

- **Error Handling:**  
  - Handle incorrect usernames or passwords gracefully with descriptive error messages.  

---

### **Instructions for PR**
- Use postman for validating the endpoints
- Attach screenshots of postman displaying the response received in both the cases of success or failure 
- DM me on discord for the current .env 
- Update the [API_ENDPOINTS.md]([API_ENDPOINTS.md) with login routes with the success and failure responses.

**Comment by Sarvesh0955** [comment]
claim

**Comment by 07CalC** [comment]
Claim

**Comment by HGRgamer** [comment]
claim

**Comment by HGRgamer** [comment]
@Buddha-11 please close the issue #3 
It is not marked done

**Comment by Buddha-11** [comment]
sorry for the inconvenience guys , just making sure if the opencode issue limits are being followed here , please be patient

**Comment by Buddha-11** [comment]
@Sarvesh0955 Assigning to you as you are the first person to claim with less than 3 current issues assigned

**Comment by Buddha-11** [comment]
@Darkknight0125 You already have 3 issues assigned , finish those and then you are welcome here :)

**Comment by Darkknight0125** [comment]
I have made my pr in skill sync backend. Comeon it's not my fault it's not yet merged 🥲

**Comment by Darkknight0125** [comment]
Thanks for the efforts tho. Had them marked as unsolved since the morning.

**Comment by official-ashutosh** [comment]
claim
